/* eslint-disable @typescript-eslint/no-unused-vars */
'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { Box } from '@mui/material'
import CustomTextField from 'src/components/text-field'
import { ReactNode } from 'react'
import NotAppLayout from 'src/views/layouts/NotAppLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Button variant='contained'>Hello world</Button> */}

      <Box sx = {{margin : 6, width: "200px"}}>
        <CustomTextField id='outlined-disabled' label='Disabled'></CustomTextField>
      </Box>
    </>
  )
}

Home.getLayout = (page: ReactNode) => <NotAppLayout>{page}</NotAppLayout>
